// Package web_test verifies the real cross-package artifact boundary: the
// frontend built by Vite must be embedded and servable by the Go HTTP package.
package web_test

import (
	"io/fs"
	"net/http"
	"net/http/httptest"
	"regexp"
	"strings"
	"testing"

	"github.com/snaraj/website-infrastructure/websites/lidersea.com/internal/server"
	website "github.com/snaraj/website-infrastructure/websites/lidersea.com/internal/web"
)

// builtAssetReference finds Vite's content-addressed script and stylesheet URLs
// without coupling the test to hashes that legitimately change on every build.
var builtAssetReference = regexp.MustCompile(`(?:src|href)="(/assets/[^"]+)"`)

// contentHashedAsset protects the one-year immutable-cache promise made by the
// Go server. A future bundler change must not publish mutable names under it.
var contentHashedAsset = regexp.MustCompile(
	`^/assets/(?:[A-Za-z0-9._-]+/)*[A-Za-z0-9._-]+-[A-Za-z0-9_-]{8,}\.[A-Za-z0-9]+$`,
)

// strongETag is the quoted SHA-256 identity generated by serveBytes. Matching
// it across GET and HEAD keeps caches and release probes deterministic.
var strongETag = regexp.MustCompile(`^"[0-9a-f]{64}"$`)

// expectedOriginHeaders is the complete browser-facing policy shared by the
// generated shell and its immutable resources at the production Go boundary.
var expectedOriginHeaders = map[string]string{
	"Content-Security-Policy":      "default-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; object-src 'none'",
	"Cross-Origin-Resource-Policy": "same-origin",
	"Permissions-Policy":           "camera=(), geolocation=(), microphone=()",
	"Referrer-Policy":              "no-referrer",
	"Strict-Transport-Security":    "max-age=31536000",
	"X-Content-Type-Options":       "nosniff",
	"X-Frame-Options":              "DENY",
}

// assertServedFile proves that GET and HEAD expose the same immutable identity,
// cache policy, content metadata, and browser-security boundary for one file.
func assertServedFile(t *testing.T, handler http.Handler, publicPath, cacheControl string) {
	t.Helper()

	response := httptest.NewRecorder()
	handler.ServeHTTP(response, httptest.NewRequest(http.MethodGet, publicPath, nil))
	if response.Code != http.StatusOK || response.Body.Len() == 0 {
		t.Errorf("asset %s = status %d, %d bytes", publicPath, response.Code, response.Body.Len())
	}
	if got := response.Header().Get("Content-Type"); got == "" {
		t.Errorf("asset %s has no Content-Type", publicPath)
	}
	if got := response.Header().Get("Cache-Control"); got != cacheControl {
		t.Errorf("asset %s Cache-Control = %q, want %q", publicPath, got, cacheControl)
	}
	if etag := response.Header().Get("ETag"); !strongETag.MatchString(etag) {
		t.Errorf("asset %s ETag = %q", publicPath, etag)
	}
	for name, expected := range expectedOriginHeaders {
		if got := response.Header().Get(name); got != expected {
			t.Errorf("asset %s %s = %q, want %q", publicPath, name, got, expected)
		}
	}

	head := httptest.NewRecorder()
	handler.ServeHTTP(head, httptest.NewRequest(http.MethodHead, publicPath, nil))
	if head.Code != http.StatusOK || head.Body.Len() != 0 {
		t.Errorf("HEAD %s = status %d, %d bytes", publicPath, head.Code, head.Body.Len())
	}
	for _, name := range []string{"Content-Type", "Cache-Control", "ETag"} {
		if head.Header().Get(name) != response.Header().Get(name) {
			t.Errorf("HEAD %s %s does not match GET", publicPath, name)
		}
	}
	for name, expected := range expectedOriginHeaders {
		if got := head.Header().Get(name); got != expected {
			t.Errorf("HEAD %s %s = %q, want %q", publicPath, name, got, expected)
		}
	}
}

// TestBuiltFrontendIsEmbeddedAndServed proves that CI is testing the production
// bundle, its immutable assets, and both lines of the static application fallback.
func TestBuiltFrontendIsEmbeddedAndServed(t *testing.T) {
	assets, err := website.FileSystem()
	if err != nil {
		t.Fatalf("FileSystem() error = %v", err)
	}
	siteHandler, err := server.New(assets)
	if err != nil {
		t.Fatalf("server.New() error = %v; run the pinned frontend build before Go tests", err)
	}

	root := httptest.NewRecorder()
	siteHandler.ServeHTTP(root, httptest.NewRequest(http.MethodGet, "/", nil))
	if root.Code != http.StatusOK {
		t.Fatalf("root status = %d", root.Code)
	}
	if got := root.Header().Get("Content-Type"); !strings.HasPrefix(got, "text/html") {
		t.Errorf("root Content-Type = %q", got)
	}
	if got := root.Header().Get("Cache-Control"); got != "no-store" {
		t.Errorf("root Cache-Control = %q", got)
	}
	if etag := root.Header().Get("ETag"); !strongETag.MatchString(etag) {
		t.Errorf("root ETag = %q", etag)
	}
	for name, expected := range expectedOriginHeaders {
		if got := root.Header().Get(name); got != expected {
			t.Errorf("root %s = %q, want %q", name, got, expected)
		}
	}
	body := root.Body.String()
	for _, required := range []string{"data-static-fallback", "Hello World!", "Website coming soon!"} {
		if !strings.Contains(body, required) {
			t.Fatalf("built root lacks %q: %q", required, body)
		}
	}
	if strings.Contains(body, "/src/main.ts") {
		t.Fatalf("built root still references a development entrypoint: %q", body)
	}

	references := builtAssetReference.FindAllStringSubmatch(body, -1)
	if len(references) < 2 {
		t.Fatalf("built root has fewer than two generated asset references: %q", body)
	}
	referencedAssets := make(map[string]struct{}, len(references))
	for _, reference := range references {
		if !contentHashedAsset.MatchString(reference[1]) {
			t.Errorf("asset reference is not content-addressed: %s", reference[1])
		}
		referencedAssets[reference[1]] = struct{}{}
	}

	servedFiles := make(map[string]struct{})
	if err := fs.WalkDir(assets, ".", func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || path == "index.html" || path == ".gitkeep" {
			return nil
		}
		if strings.HasPrefix(entry.Name(), ".") {
			t.Errorf("unexpected hidden embedded file: %s", path)
			return nil
		}

		publicPath := "/" + strings.TrimPrefix(path, "./")
		cacheControl := "no-cache"
		if strings.HasPrefix(publicPath, "/assets/") {
			if !contentHashedAsset.MatchString(publicPath) {
				t.Errorf("embedded immutable asset is not content-addressed: %s", publicPath)
			}
			cacheControl = "public, max-age=31536000, immutable"
		}
		servedFiles[publicPath] = struct{}{}
		assertServedFile(t, siteHandler, publicPath, cacheControl)
		return nil
	}); err != nil {
		t.Fatalf("walk embedded frontend: %v", err)
	}
	for reference := range referencedAssets {
		if _, found := servedFiles[reference]; !found {
			t.Errorf("index references an unembedded asset: %s", reference)
		}
	}

	rootHead := httptest.NewRecorder()
	siteHandler.ServeHTTP(rootHead, httptest.NewRequest(http.MethodHead, "/", nil))
	if rootHead.Code != http.StatusOK || rootHead.Body.Len() != 0 {
		t.Errorf("HEAD / = status %d, %d bytes", rootHead.Code, rootHead.Body.Len())
	}
	if rootHead.Header().Get("ETag") != root.Header().Get("ETag") {
		t.Error("HEAD / ETag does not match GET")
	}

	placeholder := httptest.NewRecorder()
	siteHandler.ServeHTTP(placeholder, httptest.NewRequest(http.MethodGet, "/.gitkeep", nil))
	if placeholder.Code != http.StatusNotFound {
		t.Errorf("embedded .gitkeep status = %d", placeholder.Code)
	}
	for _, sourcePath := range []string{"/src/main.ts", "/assets/application.js.map"} {
		response := httptest.NewRecorder()
		siteHandler.ServeHTTP(response, httptest.NewRequest(http.MethodGet, sourcePath, nil))
		if response.Code != http.StatusNotFound {
			t.Errorf("source artifact %s status = %d", sourcePath, response.Code)
		}
	}
}
