apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cloudflared-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflare-public.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cloudflare-public.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cloudflared-edge
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflare-public.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cloudflare-public.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Egress]
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 100.64.0.0/10
              - 127.0.0.0/8
              - 169.254.0.0/16
              - 172.16.0.0/12
              - 192.168.0.0/16
              - 224.0.0.0/4
              - 240.0.0.0/4
      ports:
        - port: 7844
          protocol: TCP
        - port: 7844
          protocol: UDP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cloudflared-naranjo-online
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflare-public.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cloudflare-public.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.origin.namespace }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.origin.podLabels | nindent 14 }}
      ports:
        - port: {{ .Values.origin.port }}
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cloudflared-lidersea-com
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflare-public.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cloudflare-public.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.liderseaOrigin.namespace }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.liderseaOrigin.podLabels | nindent 14 }}
      ports:
        - port: {{ .Values.liderseaOrigin.port }}
          protocol: TCP
