apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflare-public.labels" . | nindent 4 }}
automountServiceAccountToken: false
