apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cloudflared-to-naranjo-online
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "naranjo-online.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "naranjo-online.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cloudflare-public
          podSelector:
            matchLabels:
              app.kubernetes.io/name: cloudflare-public
      ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
