apiVersion: v1
kind: Service
metadata:
  name: naranjo-online
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "naranjo-online.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "naranjo-online.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
