apiVersion: v1
kind: ServiceAccount
metadata:
  name: naranjo-online
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "naranjo-online.labels" . | nindent 4 }}
automountServiceAccountToken: false
