apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: naranjo-online-source
  namespace: naranjo-online
spec:
  # This source may archive only the released naranjo.online chart subtree.
  ignore: |
    /*
    !/chart
  interval: 10m0s
  ref:
    branch: main
  sparseCheckout:
    - chart
  timeout: 60s
  url: https://github.com/snaraj/naranjo.online.git
